/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadoramas;

/**
 *
 * @author Melany <melanyjumbo13@gmail.com>
 */
public class Calculator extends javax.swing.JFrame {
    
    private float operando1;
    private float operando2;
    private String operador;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }
    
     public String validacionEntero(float calculo){
        String respuesta;
        respuesta = Float.toString(calculo);//esto guarda 
        if(calculo % 1 == 0){
            respuesta = respuesta.substring(0, respuesta.length()-2);
        }
        return respuesta;
     }
    
     public int calculadorMCD(int operad1, int operad2){
        while (operad2 != 0) {
            int calculadormcm = operad2;
            operad2 = operad1 % operad2;
            operad1 = calculadormcm;
        }
        return operad1;
     }
     public int calculadorMCM(int operad1, int operad2) {
        if (operad1 == 0 || operad2 == 0){
        return 0;
        }return Math.abs(operad1 * operad2) / calculadorMCD(operad1, operad2);
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pantalla1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnExponencial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pantalla2 = new javax.swing.JLabel();
        btnmcm = new javax.swing.JButton();
        btnmcd = new javax.swing.JButton();
        btnEspacio = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnClearOp = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        pantalla3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(253, 226, 187));
        jTabbedPane1.setForeground(new java.awt.Color(158, 96, 5));
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jPanel1.setBackground(new java.awt.Color(253, 235, 219));

        pantalla1.setBackground(new java.awt.Color(254, 248, 241));
        pantalla1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pantalla1.setForeground(new java.awt.Color(110, 73, 20));
        pantalla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 145, 6)));
        pantalla1.setOpaque(true);

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(161, 104, 10));
        btnClear.setText("C");
        btnClear.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDivision.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(161, 104, 10));
        btnDivision.setText("/");
        btnDivision.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnMulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(161, 104, 10));
        btnMulti.setText("*");
        btnMulti.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnResta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnResta.setForeground(new java.awt.Color(161, 104, 10));
        btnResta.setText("-");
        btnResta.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(161, 104, 10));
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(161, 104, 10));
        btn8.setText("8");
        btn8.setToolTipText("");
        btn8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(161, 104, 10));
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(161, 104, 10));
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(161, 104, 10));
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(161, 104, 10));
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(161, 104, 10));
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(161, 104, 10));
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(161, 104, 10));
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(161, 104, 10));
        btnSuma.setText("+");
        btnSuma.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(161, 104, 10));
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPunto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(161, 104, 10));
        btnPunto.setText(".");
        btnPunto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(161, 104, 10));
        btnIgual.setText("=");
        btnIgual.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnRaiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRaiz.setForeground(new java.awt.Color(161, 104, 10));
        btnRaiz.setText("√");
        btnRaiz.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnExponencial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExponencial.setForeground(new java.awt.Color(161, 104, 10));
        btnExponencial.setText("xⁿ");
        btnExponencial.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(254, 244, 230), new java.awt.Color(236, 157, 28)));
        btnExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExponencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExponencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculadora", jPanel1);

        jPanel2.setBackground(new java.awt.Color(252, 239, 220));

        pantalla2.setBackground(new java.awt.Color(254, 250, 243));
        pantalla2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pantalla2.setForeground(new java.awt.Color(63, 107, 142));
        pantalla2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 174, 44)));
        pantalla2.setOpaque(true);

        btnmcm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnmcm.setForeground(new java.awt.Color(170, 100, 13));
        btnmcm.setText("mcm");
        btnmcm.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnmcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmcmActionPerformed(evt);
            }
        });

        btnmcd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnmcd.setForeground(new java.awt.Color(170, 100, 13));
        btnmcd.setText("mcd");
        btnmcd.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnmcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmcdActionPerformed(evt);
            }
        });

        btnEspacio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEspacio.setForeground(new java.awt.Color(170, 100, 13));
        btnEspacio.setText("Espacio");
        btnEspacio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspacioActionPerformed(evt);
            }
        });

        btnSiete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSiete.setForeground(new java.awt.Color(170, 100, 13));
        btnSiete.setText("7");
        btnSiete.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnClearOp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClearOp.setForeground(new java.awt.Color(170, 100, 13));
        btnClearOp.setText("C");
        btnClearOp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnClearOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOpActionPerformed(evt);
            }
        });

        btnOcho.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnOcho.setForeground(new java.awt.Color(170, 100, 13));
        btnOcho.setText("8");
        btnOcho.setToolTipText("");
        btnOcho.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnNueve.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNueve.setForeground(new java.awt.Color(170, 100, 13));
        btnNueve.setText("9");
        btnNueve.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        btnCuatro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCuatro.setForeground(new java.awt.Color(170, 100, 13));
        btnCuatro.setText("4");
        btnCuatro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnCinco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCinco.setForeground(new java.awt.Color(170, 100, 13));
        btnCinco.setText("5");
        btnCinco.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSeis.setForeground(new java.awt.Color(170, 100, 13));
        btnSeis.setText("6");
        btnSeis.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnUno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUno.setForeground(new java.awt.Color(170, 100, 13));
        btnUno.setText("1");
        btnUno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnDos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDos.setForeground(new java.awt.Color(170, 100, 13));
        btnDos.setText("2");
        btnDos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnTres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTres.setForeground(new java.awt.Color(170, 100, 13));
        btnTres.setText("3");
        btnTres.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnCero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCero.setForeground(new java.awt.Color(170, 100, 13));
        btnCero.setText("0");
        btnCero.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(252, 237, 198), new java.awt.Color(227, 165, 28)));
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        pantalla3.setBackground(new java.awt.Color(254, 249, 241));
        pantalla3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pantalla3.setForeground(new java.awt.Color(63, 107, 142));
        pantalla3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 188, 61)));
        pantalla3.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 93, 1));
        jLabel1.setText("RESULTADO");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 93, 1));
        jLabel2.setText("VALORES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnClearOp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnmcm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnmcd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pantalla3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pantalla3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearOp, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmcm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmcd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Operaciones", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.pantalla1.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        operando1 = Float.parseFloat(this.pantalla1.getText());
        this.operador = "/";
        this.pantalla1.setText("");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        operando1 = Float.parseFloat(this.pantalla1.getText());
        this.operador = "*";
        this.pantalla1.setText("");
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        operando1 = Float.parseFloat(this.pantalla1.getText());
        this.operador = "-";
        this.pantalla1.setText("");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        operando1 = Float.parseFloat(this.pantalla1.getText());
        this.operador = "+";
        this.pantalla1.setText("");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        this.pantalla1.setText(this.pantalla1.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if(!this.pantalla1.getText().contains(".")){
            this.pantalla1.setText(this.pantalla1.getText()+".");
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        operando2 = Float.parseFloat(this.pantalla1.getText());
        switch(this.operador){
            case "+":
                this.pantalla1.setText(validacionEntero(operando1 + operando2));
                break;
            case "-":
                this.pantalla1.setText(validacionEntero(operando1 - operando2));
                break;
            case "*":
                this.pantalla1.setText(validacionEntero(operando1 * operando2));
                break;
            case "/":
                if(operando2 == 0){
                this.pantalla1.setText("No se puede dividir para cero");
                }else{
                this.pantalla1.setText(validacionEntero(operando1 / operando2));
                }
                break;
            case "xⁿ":
                double res = (float)Math.pow(operando1, operando2);
                this.pantalla1.setText(String.valueOf(res));
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnmcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmcmActionPerformed
        try {
             operando2 = Float.parseFloat(this.pantalla2.getText());
             int num1 = (int)operando1; 
             int num2 = (int)operando2;        
             this.pantalla3.setText(num1+"  "+num2);
             
            if (num1 == 0 || num2 == 0) {
                this.pantalla2.setText("0");
            } else {
                int resMCM = calculadorMCM(num1, num2);
                this.pantalla2.setText("MCM: "+validacionEntero((float)resMCM));
            }
             } catch (NumberFormatException e) {
             this.pantalla2.setText("Número inválido");
             }
    }//GEN-LAST:event_btnmcmActionPerformed

    private void btnmcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmcdActionPerformed
        try {
        operando2 = Float.parseFloat(this.pantalla2.getText());
        int num1 = (int)operando1; 
        int num2 = (int)operando2;        
        this.pantalla3.setText(num1+"  "+num2);

        if(operando2 == 0){
            this.pantalla2.setText("No se puede dividir para cero");
        }else{
            int resultado = calculadorMCD(num1, num2);
            this.pantalla2.setText("MCD: "+validacionEntero((float)resultado));
        }
        } catch (NumberFormatException e) {
        this.pantalla2.setText("Número inválido");
        }
        
    }//GEN-LAST:event_btnmcdActionPerformed

    private void btnEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspacioActionPerformed
        operando1 = Float.parseFloat(this.pantalla2.getText());
        //this.operador = "MCD";
        this.pantalla2.setText("");
        
    }//GEN-LAST:event_btnEspacioActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnClearOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOpActionPerformed
        this.pantalla2.setText("");
        this.pantalla3.setText("");

    }//GEN-LAST:event_btnClearOpActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        this.pantalla2.setText(this.pantalla2.getText()+"0");
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        if(!pantalla1.getText().isEmpty()){ //Se verifica si esta vacia la pantalla1
            double valor = Double.parseDouble(this.pantalla1.getText()); //Se guarda el valor de pantalla1, pasado de String a double
            if(valor < 0){
                this.pantalla1.setText("No se pueden ingresar numeros negativos"); //condición 
            }else{
                double res = Math.sqrt(valor); //operación mediante la funcion matemática, que permite calcular la raíz
                this.pantalla1.setText(String.valueOf(res));//pasa de souble a String 
            }
        }
        
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponencialActionPerformed
        operando1 = Float.parseFloat(this.pantalla1.getText());
        this.operador = "xⁿ";
        this.pantalla1.setText("");
    }//GEN-LAST:event_btnExponencialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearOp;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnEspacio;
    private javax.swing.JButton btnExponencial;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnmcd;
    private javax.swing.JButton btnmcm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel pantalla1;
    private javax.swing.JLabel pantalla2;
    private javax.swing.JLabel pantalla3;
    // End of variables declaration//GEN-END:variables
}
